name: "dev-tools"

services:
  traefik:
    container_name: "dev-tools-traefik"
    image: traefik:v2.10
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: "${TIMEZONE:-Europe/Berlin}"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./docker/development/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./docker/development/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro"
      - "./docker/development/traefik/certs:/etc/certs:ro"
    networks:
      - "proxy"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

  buggregator:
    image: ghcr.io/buggregator/server:latest
    container_name: dev-tools-buggregator
    restart: unless-stopped
    ports:
      - 8000:8000
      - 1025:1025
      - 9912:9912
      - 9913:9913
    networks:
      - "proxy"
      - "develop"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.buggregator.rule=Host(`${BUGGREGATOR_URL:-buggregator.app.loc}`)"
      - "traefik.http.services.buggregator.loadbalancer.server.port=${BUGGREGATOR_HTTP_PORT:-8000}"
      - "traefik.http.routers.buggregator.entrypoints=https"
      - "traefik.http.routers.buggregator.tls=true"

networks:
  proxy:
    external: true
  develop:
    external: true
