# Dynamic configuration
http:
  routers:
    traefik:
      rule: "Host(`traefik.app.loc`)"
      service: "api@internal"
      tls:
        domains:
          - main: "app.loc"
            sans:
              - "*.app.loc"
tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
